spring:
  message: Hello, this is message from department spring cloud bus
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 172.23.16.1
    instance-id: ${spring.application.name}:${server.port}



